# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink: /blog/:categories/:title.html

# Pages list
pages_list:       
  Research: '/research.html'
  Teaching: '/teaching.html'
  CV: '/cv.html'
  Blog: '/blog'
  Contact: '/contact.html'
  #Feed: '/blog/atom.xml'
  

# Setup
title:            Darya Vanichkina 
tagline:          'Bioinformatics PhD student'
description:      'lncRNA RNA-seq addict #Bioinformatics PhD student. Weekend ardent bushwalker, art & book lover.'
url:              http://daryavanichkina.com
baseurl:          '/'
paginate:         5
paginate_path: "/blog/page:num"

author:
  name:           'Darya Vanichkina'
  url:            https://twitter.com/dvanichkina

# Custom vars

